[workspace]

members = [
    "packages/client",
    "packages/core",
    "packages/wasm",
    "packages/resolvers",
    "packages/msgpack",
    "packages/manifest",
    "packages/plugin",
    "packages/plugins/http",
    "packages/builder"
]