[package]
name = "polywrap_core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.37"
regex = "1.6.0"
async-trait = "0.1.57"
polywrap_msgpack = { path = "../msgpack" }
polywrap_manifest = { path = "../manifest" }
serde_json = "1.0.87"
jsonschema = "0.16.1"